### ISSUE TITLE
Support for Lightsys+ / RP432MP panel

### ISSUE THREAD

**Issue by RobBie1221** [vanackej/risco-lan-bridge#6]
I have a RP432MP (Lightsys+) panel that I would like to have supported.

It seems it has only minor changes to the RP432 panel (number of zones, outputs). I can make the necessary changes and test.
@vanackej Are you still actively maintaining this and the risco-mqtt-local repo? If I create a pull request, can you merge and create a new release?

**Comment by RobBie1221** [comment]
Never mind, found a more recent fork

**Comment by vanackej** [comment]
Hi. I still maintain this module when I get some free time, especially if people submit ready to merge pull requests. But if you prefer contributing to a fork that's ok for me too. 

Some people are using the proxy mode (useful only if you have a cloud subscription and some old TCP adapters), but as I don't have this setup myself, I can't test and debug it, so I believe some forks are maintaining/improving the stability of the proxy mode => That's the more "recent fork" you are talking about.

If no proxy mode requirements, and using Home Assistant, I would rather recommend using the official integration, that also supports the local API.
